config/routes.rb
Rails.application.routes.draw do

  resources :jobs, :boats

  devise_for :users
  
  root to: "boats#index"

  post 'boats/add_job'

  post 'boats/remove_job'

  post 'jobs/add_boat'

  post 'jobs/remove_boat'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord

	belongs_to :user
	has_and_belongs_to_many :jobs

	has_attached_file :avatar,
	:storage => :s3,
	:s3_region => "us-east-1",
	:s3_credentials => {
		# :s3_host_name => "s3.us-east-1.amazonaws.com",
		:bucket => "shipping-app-paul",
		:access_key_id => ENV['IAM_KEY'],
		:secret_access_key => ENV['IAM_SECRET_KEY'],
	}

	validates_attachment_content_type :avatar,
	:content_type => /\Aimage\/.*\Z/

end

app/models/job.rb
class Job < ApplicationRecord

	belongs_to :user
	has_and_belongs_to_many :boats

	validates :description, presence: true, length: { minimum: 50 }
    validates :origin, presence: true
    validates :cost, presence: true, numericality: true
    validates :destination, presence: true
    validates :container_amount, presence: true, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
  has_many :boats
end

app/controllers/Users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
    # super   
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    # super
    redirect_to root_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController

  def index
      @boats = Boat.all
  end

  def show
    @boat = Boat.find(params[:id])
  end

  def new
    @boat = Boat.new
  end

  def create
    @boat = Boat.create(boats_params)
    redirect_to boats_path
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private


  def boats_params
    params.require(:boat).permit(:name, :location, :container_max, :user_id, :avatar)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  end

  def show
    @job = Job.find(params[:id])
    @boats = Boat.where(user_id: current_user.id)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.create(job_params)
    if @job.save
    flash[:notice] = "Job Successfully Created"
    redirect_to root_path
    else 
    redirect_back(fallback_location: new_boat_path)
    flash[:joberror] = "Please Add Description"
    end 
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def add_boat
    @job = Job.find(params[:job_id])
    @boat = Boat.find(params[:boat_id])
    @job.available = false
    @job.save
    @boat.jobs.push(@job)
    redirect_to @job
  end

  def remove_boat
    @job = Job.find(params[:job_id])
    @boat = Boat.find(params[:boat_id])
    @job.available = true
    @job.save
    @boat.jobs.delete(@job)
    redirect_to @job
  end
  
  private

  def job_params
    params.require(:job).permit(:description, :origin, :destination, :container_amount, :cost, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def locations
		locations = ["Buenos Aires", "Cape Town", "Dubai", "Hong Kong", "Mombasa", "New York", "Shanghai", "Tokyo", "Philadelphia"].sort
	end

	def contain_max_random 
		rand(5..18000)
	end

	def contain_amount 
		rand(5..100)
	end

	def cost_amount
		rand(500..100000)
	end

	def random_string
		(0...17).map { (65 + rand(26)).chr }.join + " " + (0...17).map { (65 + rand(26)).chr }.join + " " + (0..18).map { (65 + rand(26)).chr }.join 
	end
end

app/helpers/boats_helper.rb
module BoatsHelper
end




 

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/boats/_newboat.html.erb
<% if current_user %>

<div class="new_boat">
<%= form_for Boat.new do |f| %>

		<h1>Create A New Boat</h1>
		<p><%= flash[:boaterror] if flash[:boaterror] %></p>
		<%= f.label :name, value: 'Boat Name' %>
		<%= f.text_field :name %>

		<%= f.label "Add Photo" %>
		<%= f.file_field :avatar %>

		<%= f.label :location, value: "Starting Location" %>
		<%= f.select(:location, options_for_select(locations)) %>


		<%= f.label :container_max %>
		<%= f.number_field :container_max, min: 5, max: 18000 %>


		<%= f.hidden_field :user_id, value: current_user.id %>


		<%= f.submit class: 'submit_button' %>

	<% end %>
<% end %>
</div>

app/views/boats/destroy.html.erb
<h1>Boats#destroy</h1>
<p>Find me in app/views/boats/destroy.html.erb</p>

app/views/boats/edit.html.erb
<h1>Boats#edit</h1>
<p>Find me in app/views/boats/edit.html.erb</p>

<%= render 'newboat' %>

app/views/boats/index.html.erb
<h1>Boats</h1>


<%= link_to "We Bought A Boat", new_boat_path %>

<h2>Last Boats</h2>
<% @boats.last(5).each do |boat| %>
<div class="boats">
	<div class="boat_name">
		<p><a><%= boat.name %></a></p>
	</div>
	<%= image_tag boat.avatar.url %>
	<div class="boat_location">
		<p>Location: <a><%= boat.location %></a></p>
	</div>
	<div class="boat_max">
		<p>Max: <%= boat.container_max %> Containers</p>
	</div>
</div>

<% end %>

<div class="empty">
</div>

<% if current_user %>
<h2>Your Boats</h2>
<% current_user.boats.each do |boat| %>
<div class="boats">
	<div class="boat_name">
		<%= link_to("/boats/#{boat.id}", {method: :get}) do %>
		<p><%= boat.name %></p>
		<% end %>
	</div>
	<%= image_tag boat.avatar.url %>
	<div class="boat_location">
		<p>Location: <a href="https://en.wikipedia.org/wiki/<%= boat.location.gsub(' ','_') %>"> <%= boat.location %></a></p>
	</div>
	<div class="boat_max">
		<p>Max: <%= boat.container_max %> Containers</p>
	</div>
</div>

<% end %>
<% end %>

app/views/boats/new.html.erb
<h1>Create A New Boat</h1>
<% if current_user %>

<div class="new_boat">
	<%= form_for Boat.new do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label "Avatar" %>
	<%= f.file_field :avatar %>
	
	<%= f.label :location, value: "Starting Location:" %>
	<%= f.select(:location, options_for_select(locations)) %>


	<%= f.label :container_max %>
	<%= f.number_field :container_max, min: 5, max: 18000 %>

	<%= f.hidden_field :user_id, value: current_user.id %>


	<%= f.submit %>

	<% end %>
	<% end %>
</div>

app/views/boats/show.html.erb
<% if current_user %>
<div class="container">
	<div class="row boat_info">
		<div class="col-sm-4 col-sm-offset-4">
			<div class="boat_name">
				<h1><%= @boat.name %></h1>
			</div>
			<img class="boat_image" src="<%=@boat.avatar.url%>">
			<div class="boat_location">
				<h3>Boat Location: <%= @boat.location %></h3>
			</div>
			<div class="boat_max">
				<h3>Maximum Containers: <%= @boat.container_max %></h3>
			</div>
			<div class="boat_amount">
				<h3>Containers Assigned: <%= @containers_assigned %></h3>
			</div>
			<% if @containers_assigned <= @boat.container_max %>
			<div class="ship_btn">
				<button>Confirm Shipment</button>
			</div>
			<% end %>

			<div class="container">
				<div class="row boat_info">
					<div class="col-sm-4 col-sm-offset-4">
						<div class="boat_name">
							<h1><%= @boat.name.capitalize %></h1>
						</div>
						<div class="boat_location">
							<h3>Boat Location: <%= @boat.location.capitalize %></h3>
						</div>
						<div class="boat_max">
							<h3>Maximum Containers: <%= @boat.container_max %></h3>
						</div>
						<div class="boat_amount">
							<h3>Containers Assigned: <%= @containers_assigned %></h3>
						</div>
						<% if @containers_assigned <= @boat.container_max %>
						<div class="ship_btn">
							<button>Confirm Shipment</button>

						</div>
						<% end %>
					</div>
				</div>
				<div class="row jobs">
					<h2> This boat's jobs: </h2>
					<% @boat.jobs.each do |job| %>
					<div class="job col-sm-3">
						<div class="job_description">
							<p> <%= job.description[0..40] %>...</p>
						</div>
						<div class="job_containers">
							<p><%= job.container_amount %> containers </p>
						</div>
						<div class="add_or_remove_btn">
							<%= form_tag boats_remove_job_path do %>
							<%= hidden_field_tag :job_id, job.id %>
							<%= hidden_field_tag :boat_id, @boat.id%>
							<%= submit_tag "Remove Job From Boat" %>
							<% end %>
						</div>
					</div>
					<% end %>
				</div>
				<div class="row jobs">
					<h2> Jobs you can add: </h2>
					<% @jobs.each do |job| %>
					<% if job.available == true %>
					<div class="job col-sm-3">
						<div class="job_description">
							<p> <%= job.description[0..40] %>...</p>
						</div>
						<div class="job_containers">
							<p><%= job.container_amount %> containers </p>
						</div>
						<div class="add_or_remove_btn">
							<%= form_tag boats_add_job_path do %>
							<%= hidden_field_tag :job_id, job.id %>
							<%= hidden_field_tag :boat_id, @boat.id%>
							<%= submit_tag "Add Job to Boat" %>
							<% end %>
						</div>
					</div>
					<% end %>
					<% end %>
				</div>
			</div>
			<% end %>

app/views/boats/update.html.erb
<h1>Boats#update</h1>
<p>Find me in app/views/boats/update.html.erb</p>

app/views/jobs/_jobform.html.erb
<% if current_user %>
	<div class="new_job">
	<%= form_for @job do |f| %>

		<h1>Create A New Job</h1>
		<p><%= flash[:joberror] if flash[:joberror] %></p>
		<%= f.label :origin, value: "Origin" %>
		<%= f.select(:origin, options_for_select(locations)) %>

		<%= f.label :destination, value: "Destination" %>
		<%= f.select(:destination, options_for_select(locations)) %>

		<%= f.text_area :description, :cols => "80", :rows => "8", value: random_string, placeholder: "Please Write 50 Characters" %>

		<%= f.label :container_amount, value: 'Container Amount' %>
		<%= f.number_field :container_amount, value: contain_amount, min: 1 %>

		<%= f.label :cost, '$' %>
		<%= f.number_field :cost, value: contain_max_random, step: 0.001, min: 1.00 %>


		<%= f.hidden_field :user_id, value: current_user.id %>

		<%= f.submit class: 'submit_button' %>
	</div>

	<% end %>
<% end %>

app/views/jobs/destroy.html.erb
<h1>Jobs#destroy</h1>
<p>Find me in app/views/jobs/destroy.html.erb</p>

app/views/jobs/edit.html.erb
<h1>Jobs#edit</h1>
<p>Find me in app/views/jobs/edit.html.erb</p>

app/views/jobs/index.html.erb
<h1>Your Jobs</h1>
	<% if current_user%>
		<% current_user.jobs.each do |job| %>
			<div class="job_description">
				<p> <%= job.description %> </p>
				<%= link_to("/jobs/#{job.id}", {method: :get}) do %>
			 	Details
		    	 <% end %>
			</div>
		<% end %>
<% end %>

app/views/jobs/new.html.erb
<%= render 'jobform' %>

app/views/jobs/show.html.erb
<% if current_user %>
<div class="container">
	<div class="row  job_show_title">
		<div class="col-sm-8 col-sm-offset-2" style="border: solid black 1px">
			<div>
				<h1> <%= @job.description %> </h1>
			</div>
		</div>
		<div class="col-sm-4 col-sm-offset-4">
			<div>
				<h3> Starting at: <%= @job.origin %> </h3>
			</div>
			<div>
				<h3> Going to: <%= @job.destination %> </h3>
			</div>
			<div>
				<h3> Number of Containers: <%= @job.container_amount %> </h3>
			</div>
			<div>
				<h3> Cost: <%= @job.cost %> </h3>
			</div>
		</div>
	</div>
	<div class="row">
		<h2> This job's boats: </h2>
		<% @job.boats.each do |boat| %>
		<div class="boat col-sm-3">
			<div class="boat_name">
				<h4><%= boat.name %></h4>
			</div>
			<div class="boat_location">
				<p>Location: <%= boat.location %></p>
			</div>
			<div class="boat_max">
				<p>Max Containers: <%= boat.container_max%></p>
			</div>
			<div class="add_or_remove_btn">
				<%= form_tag jobs_remove_boat_path do %>
				<%= hidden_field_tag :job_id, @job.id%>
				<%= hidden_field_tag :boat_id, boat.id%>
				<%= submit_tag "Remove Job from Boat"%>
				<% end %>
			</div>
		</div>
		<%end%>
	</div>
	<div class="row">
		<h2> Boats you can add this job to: </h2>
		<% @boats.each do |boat| %>
		<% if boat.available == true %>
		<div class="boat col-sm-3">
			<div class="boat_name">
				<h4><%= boat.name %></h4>
			</div>
			<div class="boat_location">
				<p>Location: <%= boat.location %></p>
			</div>
			<div class="boat_max">
				<p>Max Containers: <%= boat.container_max%></p>
			</div>
			<div class="add_or_remove_btn">
				<%= form_tag jobs_add_boat_path do %>
				<%= hidden_field_tag :job_id, @job.id%>
				<%= hidden_field_tag :boat_id, boat.id%>
				<%= submit_tag "Add Job to Boat"%>
				<% end %>
			</div>
		</div>
		<% end %>
		<%end%>
	</div>
</div>
<% end %>




<h1> jobs show</h1>
<div class="job_description">
	<p> <%= @job.description %> </p>
</div>
<div class="job_origin">
	<p> Starting at: <%= @job.origin %> </p>
</div>
<div class="job_destination">
	<p> Going to: <%= @job.destination %> </p>
</div>
<div class="job_amount">
	<p> Number of Containers: <%= @job.container_amount %> </p>
</div>
<div class="job_cost">
	<p> Cost: <%= @job.cost %> </p>
</div>
<% if @job.boats.length > 0 %>
<div class="job_boat">
	<p> Boats Using: </p>
	<% @job.boats.each do |boat| %>
	<p> <%= boat.name %> </p>
	<% end %>
	<button> Add another boat </button>
</div>
<% else %>
<div class="job_boat">
	<button> Add a boat </button>
</div>
<% end %>

app/views/jobs/update.html.erb
<h1>Jobs#update</h1>
<p>Find me in app/views/jobs/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groupship</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-fixed-top">
        <% if current_user %>
        <ul class="list-unstyled list-inline">
           <li><%= link_to(root_path, {method: :get}) do %>
            Homepage
            <% end %>
          </li>

           <li><%= link_to new_boat_path, {method: :get} do %>
            New Boat
            <% end %>
          </li>

          <li><%= link_to new_job_path, {method: :get} do %>
             New Job
            <% end %>
          </li>

          <li><%= link_to jobs_path, {method: :get} do %>
             Jobs Available
            <% end %>
          </li>

          <li class="active"><%= link_to destroy_user_session_path, {method: :delete} do %>
            Log Out
            <% end %>
            </li>
          <% else %>
          <li><%= link_to new_user_session_path, {method: :get} do %>
            Log In
            <% end %>
          </li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>

<%= yield %>


</body>
</html>